size: ${img_size}
mean: ${tuple:0.485, 0.456, 0.406}
std: ${tuple:0.229, 0.224, 0.225}
augment_cfg:
  torchvision.transforms.Resize:
    size: ${img_size}
  torchvision.transforms.ToTensor: null
  torchvision.transforms.ColorJitter:
    brightness: 0.1
    contrast: 0.1
    saturation: 0.1
    hue: 0
  torchvision.transforms.RandomRotation:
    degrees: 15
  torchvision.transforms.RandomResizedCrop:
    size: ${img_size}
    scale: ${tuple:0.9, 1.0}
    # ratio: [0.75, 1.3333333333333333]
    antialias: true
  torchvision.transforms.RandomGrayscale:
    p: 0.1
  torchvision.transforms.RandomHorizontalFlip:
    p: 0.5
  torchvision.transforms.RandomErasing:
    scale: ${tuple:0.10, 0.20}
  torchvision.transforms.Normalize:
    mean: ${tuple:0.485, 0.456, 0.406}
    std: ${tuple:0.229, 0.224, 0.225}
