# config/config.yaml
defaults:
  - _self_
  - dataset: vn3k_en
  - loss: tbps_clip
  - aug: tbps_clip
  - trainer: tbps_clip
  - optimizer: tbps_clip
  - scheduler: tbps_clip
  - tokenizer: clip
  - backbone: clip
  - logger: default

training: true
dataset_root_dir: .
distributed: false
img_size_st: "(384, 384)"
img_size: ${eval:${img_size_st}}
seed: 2307
