# Main contrastive loss
NITC: false
nitc_loss_weight: 1.0
softlabel_ratio: 0.0

MVS: false

# Self-supervised losses following SimCLR
SS: false
simclr_temperature: 0.1
ss_loss_weight: 0.4

# Masked language modeling loss
MLM: true
mlm_loss_weight: 1.0
cmt_depth: 4

ID: true
id_loss_weight: 1.0

SDM: true
sdm_loss_weight: 1.0

RITC: false
ritc_eps: 1.0e-2
ritc_loss_weight: 1.0

CITC: false
citc_inmodal_weight: 0.25
citc_intermodal_weight: 0.25
citc_loss_weight: 0.1
