# Main contrastive loss
NITC: true
nitc_loss_weight: 1.0
softlabel_ratio: 0.5

MVS: true

# Self-supervised losses following SimCLR
SS: true
simclr_temperature: 0.1
ss_loss_weight: 0.4

# Masked language modeling loss
MLM: false
mlm_loss_weight: 1.0
cmt_depth: 4

ID: false
id_loss_weight: 1.0

SDM: false
sdm_loss_weight: 1.0

RITC: false
ritc_eps: 1.0e-2
ritc_loss_weight: 1.0

CITC: true
citc_inmodal_weight: 0.25
citc_intermodal_weight: 0.25
citc_loss_weight: 0.1
